title:        'Ansal Supertramp'
tagline:      'Ansal Supertramp'
description:  'Javascript Developer'
url:          http://blog.ansals.me
markdown:     kramdown
permalink:    pretty
pygments:     true
paginate:     5
